# Generated by Django 4.1.4 on 2022-12-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='summonerName',
            field=models.CharField(max_length=30),
        ),
    ]
