# Generated by Django 4.1.4 on 2023-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_profile_gamesplayed_profile_winratepercentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='winratePercentage',
        ),
        migrations.AddField(
            model_name='profile',
            name='gamesWon',
            field=models.IntegerField(default=0),
        ),
    ]
