# Generated by Django 4.1.4 on 2023-01-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_remove_profile_winratepercentage_profile_gameswon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamesLost',
            field=models.IntegerField(default=0),
        ),
    ]
