# Generated by Django 4.1.4 on 2023-01-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='createBy',
            new_name='createdBy',
        ),
    ]
