# Generated by Django 4.1.4 on 2023-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_rename_createby_team_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
