# Generated by Django 4.1.4 on 2023-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='invited', max_length=20),
        ),
    ]
