# Generated by Django 4.1.4 on 2023-01-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
