# Generated by Django 4.1.4 on 2023-01-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_invitation_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='username',
        ),
    ]
