# Generated by Django 4.1.4 on 2023-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_invitation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='invited', max_length=20),
        ),
    ]
