# Generated by Django 4.1.5 on 2023-01-07 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0021_alter_invitation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='default_image_organizer.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, default='default_image_tournament.png', null=True, upload_to='')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('server', models.CharField(max_length=10)),
                ('maxTeams', models.IntegerField()),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.organizer')),
                ('registeredTeams', models.ManyToManyField(related_name='registeredTeams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
