# Generated by Django 4.1.5 on 2023-01-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_organizer_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registeredTeams',
            field=models.ManyToManyField(related_name='registeredTeams', to='Website.team'),
        ),
    ]
