# Generated by Django 4.1.5 on 2023-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0023_alter_tournament_registeredteams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registeredTeams',
            field=models.ManyToManyField(blank=True, related_name='registeredTeams', to='Website.team'),
        ),
    ]
