# Generated by Django 4.1.5 on 2023-01-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_alter_tournament_registeredteams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
