# Generated by Django 4.1.5 on 2023-01-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_remove_tournament_date_remove_tournament_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
