# Generated by Django 4.1.5 on 2023-01-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0026_tournament_date_tournament_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='dateTime',
        ),
    ]
