# Generated by Django 4.1.5 on 2023-01-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0027_remove_tournament_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('before_starting', 'Before_starting'), ('in_game', 'In_game'), ('completed', 'Completed')], default='before_starting', max_length=25),
        ),
    ]
