# Generated by Django 4.1.5 on 2023-01-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0028_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In_progress'), ('completed', 'Completed')], default='in_progress', max_length=25),
        ),
    ]
