# Generated by Django 4.1.5 on 2023-01-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0029_alter_tournament_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=100)),
                ('teamsInMatch', models.ManyToManyField(blank=True, related_name='teamsInMatch', to='Website.team')),
                ('tournamentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.tournament')),
            ],
        ),
    ]
