# Generated by Django 4.1.5 on 2023-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0030_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
