# Generated by Django 4.1.5 on 2023-01-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0031_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournamentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.tournament'),
        ),
    ]
