# Generated by Django 4.1.5 on 2023-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0032_alter_match_tournamentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='generatedBracket',
            field=models.BooleanField(default=False),
        ),
    ]
