# Generated by Django 4.1.5 on 2023-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0033_tournament_generatedbracket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='generatedBracket',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('end', 'End')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
