# Generated by Django 4.1.5 on 2023-01-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0034_remove_tournament_generatedbracket_match_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchName',
            field=models.CharField(default='vs', max_length=200),
        ),
    ]
