# Generated by Django 4.1.5 on 2023-01-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0035_match_matchname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='afterGameImage',
            field=models.ImageField(blank=True, default='default_image_tournament.png', null=True, upload_to=''),
        ),
    ]
