# Generated by Django 4.1.5 on 2023-01-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0036_match_aftergameimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='afterGameImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
