# Generated by Django 4.1.5 on 2023-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0040_alter_match_aftergameimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='image',
            field=models.ImageField(blank=True, default='default_image_organizer.png', null=True, upload_to='organizers_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='profiles_images'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, default='default_image_tournament.png', null=True, upload_to='tournaments_images'),
        ),
    ]
