# Generated by Django 4.1.5 on 2023-01-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0041_alter_organizer_image_alter_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pointBlue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='pointRed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
