# Generated by Django 4.1.5 on 2023-01-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0042_match_pointblue_match_pointred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pointBlue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pointRed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
