# Generated by Django 4.1.5 on 2023-01-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0044_alter_match_pointblue_alter_match_pointred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=25),
        ),
    ]
