# Generated by Django 4.1.5 on 2023-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0045_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchName',
            field=models.IntegerField(),
        ),
    ]
