# Generated by Django 4.1.5 on 2023-01-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0046_alter_match_matchname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='losser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
