# Generated by Django 4.1.5 on 2023-01-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0047_match_losser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='winRate',
            field=models.FloatField(default=0),
        ),
    ]
