# Generated by Django 4.1.5 on 2023-01-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0049_alter_profile_winrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='winRate',
        ),
    ]
