# Generated by Django 4.1.5 on 2023-01-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0050_remove_profile_winrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['rating']},
        ),
    ]
