# Generated by Django 4.1.5 on 2023-01-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0051_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
