# Generated by Django 4.1.5 on 2023-01-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0052_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
