# Generated by Django 4.1.5 on 2023-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0053_remove_tournament_date_remove_tournament_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
